stages:
  - Test and Lint
  - Build and Push 

Test and Lint:
  stage: Test and Lint
  script:
    - echo "Test and Lint"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|production)$/ || $CI_COMMIT_BRANCH =~ /^(master|production)$/'

Build and Push:
  stage: Build and Push
  script:
    - echo "Build and Push Docker Image"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|production)$/'
